plugins {
    id 'java'
    id 'org.springframework.boot' version '3.2.4'
    id 'io.spring.dependency-management' version '1.1.3'
    id "org.openapi.generator" version "7.5.0"
}

group = 'droni'
version = '0.0.1-SNAPSHOT'

java {
    sourceCompatibility = '21'
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // OpenAPI UI and codegen
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.3.0'
    // https://mvnrepository.com/artifact/javax.xml.bind/jaxb-api
    implementation group: 'javax.xml.bind', name: 'jaxb-api', version: '2.3.1'

    implementation('org.openapitools:openapi-generator:7.5.0') {
        exclude group: 'org.slf4j', module: 'slf4j-simple'
    }
    implementation "org.openapitools:openapi-generator-gradle-plugin:7.5.0"
    implementation 'org.openapitools:jackson-databind-nullable:0.2.6'

    // jpa 설정
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    // postgres driver
    implementation group: 'org.postgresql', name: 'postgresql', version: '42.7.3'

    // https://mvnrepository.com/artifact/org.hibernate/hibernate-validator
    implementation group: 'org.hibernate', name: 'hibernate-validator', version: '8.0.1.Final'

    //spring security
    implementation "org.springframework.boot:spring-boot-starter-security"
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'

    //querydsl
    implementation 'com.querydsl:querydsl-jpa:5.0.0:jakarta'
    annotationProcessor "com.querydsl:querydsl-apt:${dependencyManagement.importedProperties['querydsl.version']}:jakarta"
    annotationProcessor "jakarta.annotation:jakarta.annotation-api"
    annotationProcessor "jakarta.persistence:jakarta.persistence-api"

    //jwt
    implementation group: 'io.jsonwebtoken', name: 'jjwt-api', version: '0.11.5'
    runtimeOnly group: 'io.jsonwebtoken', name: 'jjwt-impl', version: '0.11.5'
    runtimeOnly group: 'io.jsonwebtoken', name: 'jjwt-jackson', version: '0.11.5'

    // test dependency
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework:spring-webflux'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.3.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.3.1'
}

openApiGenerate {
    generatorName.set("spring")
    library.set("spring-boot")
    inputSpec.set(project.file("$rootDir/src/main/resources/openapi.yaml").absolutePath)
    outputDir.set(project.file("$buildDir/.swagger-generated").absolutePath)
    apiPackage.set("backend.generated-api")
    modelPackage.set("backend.generated-model")
    configOptions.set([
            interfaceOnly    : "true",
            useBeanValidation: "true",
            dateLibrary      : "java8",
            useSpringBoot3   : "true",
            useTags          : "true"

    ])
}
sourceSets {
    main {
        java {
            srcDir("$buildDir/.swagger-generated/src/main/java")
        }
    }
}