spring:
  profiles:
    group:
      "local": "default,auth,local"
      "dev": "default,auth,dev"
      "rel": "default,auth,rel"
      "prod": "default,auth,prod"
---
spring:
  config:
    activate:
      on-profile: default
  application:
    name: droni-backend-api
  datasource:
    url: jdbc:postgresql://${droni.postgresql.ip}:${droni.postgresql.port}/${droni.postgresql.database}
    driver-class-name: org.postgresql.Driver
    hikari:
      max-lifetime: 50000
      maximum-pool-size: 10
  jpa:
    show-sql: false
    open-in-view: true
    database: postgresql
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080
# OpenAPI sprigDOC configuration
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
    disable-swagger-default-url: true
    display-request-duration: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
droni:
  postgresql:
    ip: localhost
    port: 5432
    database: droni

---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: validate
droni:
  postgresql:
    ip: localhost
    port: 5432
    database: droni
server:
  port: 8086
