openapi: 3.1.0
servers:
  - description: localhost
    url: http://localhost:8080
  - description: dev(ncp)
    url: http://223.130.147.166:8080
info:
  title: droni-api
  description: |
    droni-api <br />
  termsOfService: https://swagger.io/terms/
  license:
    name: Apache License Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  version: '0.0.6'
tags:
  - name: home
    description: home API
  - name: test
    description: test API
security:
  - bearer-key: []
paths:
  /home/banner:
    get:
      tags:
        - home
      summary: get banner api
      description: get banner image for home page
      operationId: getBanner
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DroniFile'
  /sucess-test:
    get:
      tags:
        - test
      description: authentication test api
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                type: string
  /expire-test:
    get:
      tags:
        - test
      description: token expired test api
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                type: string

components:
  schemas:
    DroniFile:
      title: file
      description: file object
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          example: fileName
        path:
          type: string
          example: http://filePathURL
  securitySchemes:
    bearer-key:
      type: http
      scheme: bearer
      bearerFormat: JWT

